import { Car, CarReview, PriceHistory, ForumCategory, ForumThread, ForumReply, UserProfile, SubscriptionTier } from '@/types';

export const subscriptionTiers: SubscriptionTier[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    features: [
      'Browse car listings',
      'Read basic reviews',
      'View current market prices',
      'Join forum discussions',
    ],
    stripe_price_id: '',
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 9.99,
    features: [
      'Everything in Free',
      'Access premium reviews',
      'Historical price charts',
      'Advanced search filters',
      'Save unlimited cars',
      'Priority forum support',
    ],
    stripe_price_id: 'price_pro_monthly',
  },
  {
    id: 'collector',
    name: 'Collector',
    price: 29.99,
    features: [
      'Everything in Pro',
      'Detailed market analytics',
      'Price prediction models',
      'Expert valuation reports',
      'Exclusive collector forums',
      'Early access to new listings',
      'Personal collection tracker',
    ],
    stripe_price_id: 'price_collector_monthly',
  },
];

export const cars: Car[] = [
  {
    id: '1',
    make: 'Porsche',
    model: '911 Carrera RS 2.7',
    year: 1973,
    price: 1250000,
    image_url: '/cars/porsche-911.jpg',
    category: 'classic',
    description: 'The 1973 Porsche 911 Carrera RS 2.7 is one of the most iconic sports cars ever made. Originally developed as a homologation special for racing, it featured a lightweight body, distinctive ducktail spoiler, and a powerful 2.7-liter flat-six engine. Only 1,580 units were produced, making it one of the most sought-after collector cars in the world.',
    specs: {
      engine: '2.7L Flat-6',
      horsepower: 210,
      torque: '188 lb-ft',
      transmission: '5-Speed Manual',
      drivetrain: 'RWD',
      weight: '2,116 lbs',
      zero_to_sixty: '5.8s',
      top_speed: '149 mph',
    },
    is_premium: false,
    created_at: '2024-01-15',
  },
  {
    id: '2',
    make: 'Ferrari',
    model: '250 GTO',
    year: 1962,
    price: 48000000,
    image_url: '/cars/ferrari-250-gto.jpg',
    category: 'exotic',
    description: 'The Ferrari 250 GTO is widely regarded as the holy grail of collector cars. With only 36 examples built between 1962 and 1964, it represents the pinnacle of Ferrari\'s racing heritage. Its combination of stunning design, racing pedigree, and extreme rarity has made it the most valuable car in the world.',
    specs: {
      engine: '3.0L V12',
      horsepower: 300,
      torque: '217 lb-ft',
      transmission: '5-Speed Manual',
      drivetrain: 'RWD',
      weight: '2,068 lbs',
      zero_to_sixty: '5.8s',
      top_speed: '174 mph',
    },
    is_premium: true,
    created_at: '2024-01-20',
  },
  {
    id: '3',
    make: 'Ford',
    model: 'Mustang Boss 429',
    year: 1969,
    price: 450000,
    image_url: '/cars/mustang-boss-429.jpg',
    category: 'muscle',
    description: 'The 1969 Ford Mustang Boss 429 was Ford\'s answer to the muscle car wars of the late 1960s. Built primarily to homologate the 429 semi-hemi engine for NASCAR, it featured a massive engine in a relatively compact Mustang body. With only 859 produced in 1969, it remains one of the most desirable American muscle cars.',
    specs: {
      engine: '429ci V8',
      horsepower: 375,
      torque: '450 lb-ft',
      transmission: '4-Speed Manual',
      drivetrain: 'RWD',
      weight: '3,870 lbs',
      zero_to_sixty: '6.0s',
      top_speed: '118 mph',
    },
    is_premium: false,
    created_at: '2024-02-01',
  },
  {
    id: '4',
    make: 'Mercedes-Benz',
    model: '300SL Gullwing',
    year: 1955,
    price: 1500000,
    image_url: '/cars/mercedes-300sl.jpg',
    category: 'luxury',
    description: 'The Mercedes-Benz 300SL "Gullwing" is an automotive masterpiece that combined cutting-edge technology with breathtaking design. Its iconic gullwing doors, fuel-injected straight-six engine, and tubular space frame made it the fastest production car of its era. Only 1,400 coupes were built.',
    specs: {
      engine: '3.0L Inline-6',
      horsepower: 215,
      torque: '203 lb-ft',
      transmission: '4-Speed Manual',
      drivetrain: 'RWD',
      weight: '2,850 lbs',
      zero_to_sixty: '7.0s',
      top_speed: '163 mph',
    },
    is_premium: true,
    created_at: '2024-02-10',
  },
  {
    id: '5',
    make: 'Chevrolet',
    model: 'Corvette Stingray',
    year: 1967,
    price: 350000,
    image_url: '/cars/corvette-stingray.jpg',
    category: 'sports',
    description: 'The 1967 Chevrolet Corvette Stingray represents the pinnacle of the C2 generation. With its aggressive fender flares, stunning proportions, and available L88 engine option, it is widely considered the most beautiful Corvette ever made. The big-block 427 models are particularly sought after by collectors.',
    specs: {
      engine: '427ci V8',
      horsepower: 435,
      torque: '460 lb-ft',
      transmission: '4-Speed Manual',
      drivetrain: 'RWD',
      weight: '3,150 lbs',
      zero_to_sixty: '5.5s',
      top_speed: '142 mph',
    },
    is_premium: false,
    created_at: '2024-02-15',
  },
  {
    id: '6',
    make: 'Lamborghini',
    model: 'Miura P400 SV',
    year: 1971,
    price: 3500000,
    image_url: '/cars/lamborghini-miura.jpg',
    category: 'exotic',
    description: 'The Lamborghini Miura P400 SV is the ultimate version of the car that started the supercar revolution. With its mid-mounted V12, stunning Gandini-designed bodywork, and thrilling performance, it remains one of the most beautiful and desirable cars ever created.',
    specs: {
      engine: '3.9L V12',
      horsepower: 385,
      torque: '294 lb-ft',
      transmission: '5-Speed Manual',
      drivetrain: 'RWD',
      weight: '2,850 lbs',
      zero_to_sixty: '5.5s',
      top_speed: '180 mph',
    },
    is_premium: true,
    created_at: '2024-03-01',
  },
  {
    id: '7',
    make: 'Aston Martin',
    model: 'DB5',
    year: 1964,
    price: 900000,
    image_url: '/cars/aston-martin-db5.jpg',
    category: 'luxury',
    description: 'The Aston Martin DB5 achieved legendary status as James Bond\'s car in Goldfinger. Beyond its cinematic fame, it is a genuinely magnificent grand tourer with a silky straight-six engine, elegant Touring-designed body, and luxurious interior. It represents the golden age of British motoring.',
    specs: {
      engine: '4.0L Inline-6',
      horsepower: 282,
      torque: '288 lb-ft',
      transmission: '5-Speed Manual',
      drivetrain: 'RWD',
      weight: '3,232 lbs',
      zero_to_sixty: '7.1s',
      top_speed: '145 mph',
    },
    is_premium: false,
    created_at: '2024-03-05',
  },
  {
    id: '8',
    make: 'Dodge',
    model: 'Charger R/T',
    year: 1968,
    price: 175000,
    image_url: '/cars/dodge-charger-rt.jpg',
    category: 'muscle',
    description: 'The 1968 Dodge Charger R/T is the definitive American muscle car. Made famous by its starring role in Bullitt, the second-generation Charger combined aggressive styling with brutal performance. The R/T package added the 440 Magnum V8, heavy-duty suspension, and R/T badging.',
    specs: {
      engine: '440ci V8 Magnum',
      horsepower: 375,
      torque: '480 lb-ft',
      transmission: '4-Speed Manual',
      drivetrain: 'RWD',
      weight: '3,574 lbs',
      zero_to_sixty: '6.5s',
      top_speed: '130 mph',
    },
    is_premium: false,
    created_at: '2024-03-10',
  },
  {
    id: '9',
    make: 'Jaguar',
    model: 'E-Type',
    year: 1961,
    price: 275000,
    image_url: '/cars/jaguar-e-type.jpg',
    category: 'classic',
    description: 'Enzo Ferrari himself called the Jaguar E-Type "the most beautiful car ever made." With its long bonnet, sleek lines, and impressive performance from its twin-cam inline-six, the E-Type was a sensation when it debuted at the 1961 Geneva Motor Show. It offered supercar performance at a fraction of the price of its Italian rivals.',
    specs: {
      engine: '3.8L Inline-6',
      horsepower: 265,
      torque: '260 lb-ft',
      transmission: '4-Speed Manual',
      drivetrain: 'RWD',
      weight: '2,520 lbs',
      zero_to_sixty: '6.9s',
      top_speed: '150 mph',
    },
    is_premium: false,
    created_at: '2024-03-15',
  },
  {
    id: '10',
    make: 'McLaren',
    model: 'F1',
    year: 1994,
    price: 20000000,
    image_url: '/cars/mclaren-f1.jpg',
    category: 'exotic',
    description: 'The McLaren F1 was designed with one goal: to be the ultimate road car. With its central driving position, naturally aspirated BMW V12, and extensive use of carbon fiber, it held the world speed record for production cars for over a decade. Only 106 were produced, and it remains one of the most coveted supercars ever built.',
    specs: {
      engine: '6.1L BMW V12',
      horsepower: 627,
      torque: '480 lb-ft',
      transmission: '6-Speed Manual',
      drivetrain: 'RWD',
      weight: '2,509 lbs',
      zero_to_sixty: '3.2s',
      top_speed: '240 mph',
    },
    is_premium: true,
    created_at: '2024-03-20',
  },
];

export const reviews: CarReview[] = [
  {
    id: '1',
    car_id: '1',
    user_id: 'user1',
    title: 'The Ultimate Air-Cooled Porsche Experience',
    content: 'Having owned this 1973 Carrera RS 2.7 for five years, I can say it delivers an unparalleled driving experience. The mechanical connection between driver and machine is something modern cars simply cannot replicate. The flat-six sings at high RPMs, the steering is telepathic, and every drive feels like an event. Yes, it demands respect and skill, but reward those who master it with one of the purest driving experiences on the planet.',
    rating: 5,
    pros: ['Incredible engine sound', 'Lightweight and nimble', 'Strong investment potential', 'Iconic design', 'Pure mechanical driving feel'],
    cons: ['Expensive maintenance', 'Parts are scarce', 'Not for daily driving', 'Interior is spartan'],
    is_premium: false,
    created_at: '2024-02-01',
  },
  {
    id: '2',
    car_id: '3',
    user_id: 'user2',
    title: 'Raw American Muscle at Its Finest',
    content: 'The Boss 429 is a brute. The massive engine barely fits in the engine bay, and the car makes its intentions clear from the moment you fire it up. The rumble of that semi-hemi V8 is intoxicating. It\'s not the most refined muscle car, but that\'s exactly the point. This is American engineering excess at its most wonderful.',
    rating: 4,
    pros: ['Incredible engine', 'Rare and collectible', 'Stunning presence', 'Appreciating value'],
    cons: ['Handling is basic', 'Fuel consumption is extreme', 'Not very comfortable', 'Cooling can be an issue'],
    is_premium: false,
    created_at: '2024-02-15',
  },
  {
    id: '3',
    car_id: '5',
    user_id: 'user3',
    title: 'The Most Beautiful Corvette Ever Made',
    content: 'The 1967 Stingray with the 427 big block is everything a Corvette should be. The styling is aggressive yet elegant, the big block delivers brutal acceleration, and it handles surprisingly well for a car of its era. This is the ultimate expression of the C2 Corvette, and driving it never gets old.',
    rating: 5,
    pros: ['Stunning design', 'Powerful engine options', 'Great aftermarket support', 'American icon'],
    cons: ['Build quality varies', 'Cramped cockpit', 'Drum brakes on some models', 'Values have become very high'],
    is_premium: false,
    created_at: '2024-03-01',
  },
  {
    id: '4',
    car_id: '2',
    user_id: 'user1',
    title: 'Driving the Holy Grail of Collector Cars',
    content: 'To drive a Ferrari 250 GTO is to experience automotive perfection. The V12 engine is a masterpiece of engineering, producing a sound that gives you chills. The chassis is perfectly balanced, allowing you to dance through corners with confidence. Every aspect of this car was designed for one purpose: winning races. And even 60 years later, it still feels alive in a way no modern car can match.',
    rating: 5,
    pros: ['Unmatched racing heritage', 'Sublime V12 engine', 'Perfect weight distribution', 'Ultimate collector status'],
    cons: ['Astronomical price', 'Virtually impossible to acquire', 'Insurance costs are staggering', 'Too valuable to drive regularly'],
    is_premium: true,
    created_at: '2024-03-10',
  },
  {
    id: '5',
    car_id: '7',
    user_id: 'user2',
    title: 'British Elegance Personified',
    content: 'The DB5 is more than just Bond\'s car—it\'s a masterclass in grand touring. The inline-six is silky smooth, the Superleggera body construction keeps weight down, and the interior is finished to the highest standards. Cruising through the countryside in a DB5 is one of motoring\'s great pleasures.',
    rating: 4,
    pros: ['Timeless design', 'Wonderful engine', 'Cultural icon', 'Comfortable GT'],
    cons: ['Electrical gremlins', 'Parts availability', 'Not the fastest in its class', 'Expensive to restore properly'],
    is_premium: false,
    created_at: '2024-03-20',
  },
  {
    id: '6',
    car_id: '10',
    user_id: 'user3',
    title: 'The Greatest Supercar Ever Built',
    content: 'Nothing compares to the McLaren F1. The central driving position gives you perfect visibility and an unmatched connection to the road. The BMW V12 is responsive and relentless, pulling hard all the way to its stratospheric redline. Gordon Murray created the perfect driver\'s car, and three decades later, nothing has surpassed it.',
    rating: 5,
    pros: ['Central driving position', 'Magnificent V12 engine', 'Groundbreaking engineering', 'Legendary performance'],
    cons: ['Maintenance requires specialists', 'Terrifyingly valuable', 'No modern safety aids', 'Air conditioning is weak'],
    is_premium: true,
    created_at: '2024-04-01',
  },
];

function generatePriceHistory(carId: string, startPrice: number, endPrice: number): PriceHistory[] {
  const history: PriceHistory[] = [];
  const years = 10;
  const startYear = 2015;

  for (let i = 0; i <= years * 4; i++) {
    const year = startYear + Math.floor(i / 4);
    const quarter = (i % 4) + 1;
    const month = (quarter - 1) * 3 + 1;
    const progress = i / (years * 4);
    const basePrice = startPrice + (endPrice - startPrice) * progress;
    const variance = basePrice * (Math.sin(i * 0.7) * 0.05 + (Math.random() - 0.5) * 0.03);

    history.push({
      id: `ph-${carId}-${i}`,
      car_id: carId,
      price: Math.round(basePrice + variance),
      date: `${year}-${String(month).padStart(2, '0')}-01`,
      source: 'Hagerty Valuation',
    });
  }
  return history;
}

export const priceHistories: Record<string, PriceHistory[]> = {
  '1': generatePriceHistory('1', 650000, 1250000),
  '2': generatePriceHistory('2', 28000000, 48000000),
  '3': generatePriceHistory('3', 200000, 450000),
  '4': generatePriceHistory('4', 800000, 1500000),
  '5': generatePriceHistory('5', 150000, 350000),
  '6': generatePriceHistory('6', 1800000, 3500000),
  '7': generatePriceHistory('7', 500000, 900000),
  '8': generatePriceHistory('8', 80000, 175000),
  '9': generatePriceHistory('9', 120000, 275000),
  '10': generatePriceHistory('10', 12000000, 20000000),
};

export const forumCategories: ForumCategory[] = [
  { id: '1', name: 'General Discussion', description: 'Talk about anything car-related', slug: 'general', thread_count: 156, icon: 'MessageCircle' },
  { id: '2', name: 'Classic Cars', description: 'Discussion about classic and vintage automobiles', slug: 'classics', thread_count: 89, icon: 'Clock' },
  { id: '3', name: 'Market Analysis', description: 'Discuss market trends and investment strategies', slug: 'market', thread_count: 67, icon: 'TrendingUp' },
  { id: '4', name: 'Restoration', description: 'Share restoration projects and tips', slug: 'restoration', thread_count: 124, icon: 'Wrench' },
  { id: '5', name: 'Buy & Sell', description: 'List cars for sale or wanted', slug: 'buy-sell', thread_count: 203, icon: 'DollarSign' },
  { id: '6', name: 'Events & Shows', description: 'Car shows, auctions, and meetups', slug: 'events', thread_count: 45, icon: 'Calendar' },
];

export const forumThreads: ForumThread[] = [
  {
    id: '1',
    category_id: '1',
    user_id: 'user1',
    title: 'What\'s your dream garage if money was no object?',
    content: 'Let\'s have some fun. If you could have any 5 cars in your garage, regardless of price, what would they be? Mine would be: 1. Ferrari 250 GTO, 2. McLaren F1, 3. Porsche 959, 4. Mercedes 300SL Gullwing, 5. Shelby Cobra 427',
    is_pinned: true,
    is_locked: false,
    reply_count: 47,
    created_at: '2024-01-15T10:30:00Z',
    updated_at: '2024-03-20T14:22:00Z',
    user: { id: 'user1', email: 'john@example.com', username: 'ClassicJohn', avatar_url: null, subscription_tier: 'collector', saved_cars: [], created_at: '2024-01-01' },
  },
  {
    id: '2',
    category_id: '3',
    user_id: 'user2',
    title: 'Air-cooled Porsche market: bubble or still climbing?',
    content: 'I\'ve been watching the air-cooled Porsche market closely. 911 prices have gone up significantly over the past decade. Some say it\'s a bubble ready to pop, others think there\'s still room to grow. What are your thoughts?',
    is_pinned: false,
    is_locked: false,
    reply_count: 23,
    created_at: '2024-02-10T09:15:00Z',
    updated_at: '2024-03-18T11:45:00Z',
    user: { id: 'user2', email: 'sarah@example.com', username: 'PorscheSarah', avatar_url: null, subscription_tier: 'pro', saved_cars: [], created_at: '2024-01-05' },
  },
  {
    id: '3',
    category_id: '4',
    user_id: 'user3',
    title: 'My 1967 Mustang Fastback Restoration - Full Build Thread',
    content: 'Starting a full documentation of my 1967 Mustang Fastback restoration. The car was found in a barn in Oklahoma and needs a complete rebuild. Follow along as I bring this beauty back to life!',
    is_pinned: false,
    is_locked: false,
    reply_count: 89,
    created_at: '2024-01-20T15:00:00Z',
    updated_at: '2024-03-22T09:30:00Z',
    user: { id: 'user3', email: 'mike@example.com', username: 'MustangMike', avatar_url: null, subscription_tier: 'free', saved_cars: [], created_at: '2024-01-10' },
  },
  {
    id: '4',
    category_id: '2',
    user_id: 'user1',
    title: 'The most undervalued classic cars right now',
    content: 'I think there are several classic cars that are currently undervalued relative to their significance. My top picks: early Datsun 240Z, BMW E9 3.0 CSL, Alfa Romeo GTV6, and the Lancia Fulvia. What do you think?',
    is_pinned: false,
    is_locked: false,
    reply_count: 34,
    created_at: '2024-03-01T12:00:00Z',
    updated_at: '2024-03-21T16:15:00Z',
    user: { id: 'user1', email: 'john@example.com', username: 'ClassicJohn', avatar_url: null, subscription_tier: 'collector', saved_cars: [], created_at: '2024-01-01' },
  },
  {
    id: '5',
    category_id: '5',
    user_id: 'user2',
    title: 'For Sale: 1970 Chevelle SS 454 - Numbers Matching',
    content: 'Selling my numbers-matching 1970 Chevelle SS 454 LS6. Cranberry Red with black interior. Full documentation, Protect-O-Plate, and window sticker. 78,000 original miles. Asking $185,000. Located in Southern California.',
    is_pinned: false,
    is_locked: false,
    reply_count: 12,
    created_at: '2024-03-15T08:00:00Z',
    updated_at: '2024-03-19T20:30:00Z',
    user: { id: 'user2', email: 'sarah@example.com', username: 'PorscheSarah', avatar_url: null, subscription_tier: 'pro', saved_cars: [], created_at: '2024-01-05' },
  },
];

export const forumReplies: ForumReply[] = [
  {
    id: '1',
    thread_id: '1',
    user_id: 'user2',
    content: 'Great picks! Mine would be: 1. Bugatti Type 57SC Atlantic, 2. Ferrari 250 GTO, 3. Porsche 917K, 4. Jaguar D-Type, 5. Alfa Romeo 33 Stradale. I love the pre-war and 60s era cars the most.',
    created_at: '2024-01-15T11:00:00Z',
    updated_at: '2024-01-15T11:00:00Z',
    user: { id: 'user2', email: 'sarah@example.com', username: 'PorscheSarah', avatar_url: null, subscription_tier: 'pro', saved_cars: [], created_at: '2024-01-05' },
  },
  {
    id: '2',
    thread_id: '1',
    user_id: 'user3',
    content: 'Easy: 1. Ford GT40 Mk I, 2. McLaren F1, 3. Lamborghini Miura SV, 4. 1969 Boss 429, 5. Shelby Daytona Coupe. All about that late 60s racing heritage!',
    created_at: '2024-01-15T13:30:00Z',
    updated_at: '2024-01-15T13:30:00Z',
    user: { id: 'user3', email: 'mike@example.com', username: 'MustangMike', avatar_url: null, subscription_tier: 'free', saved_cars: [], created_at: '2024-01-10' },
  },
  {
    id: '3',
    thread_id: '2',
    user_id: 'user1',
    content: 'I think air-cooled Porsches have reached a plateau but won\'t crash. The demographic that loves these cars (Gen X) is at peak earning years. Long-term, they\'ll hold value because they\'re genuinely special to drive. Not every car is a 2.7 RS though - the standard 911s might soften a bit.',
    created_at: '2024-02-10T10:30:00Z',
    updated_at: '2024-02-10T10:30:00Z',
    user: { id: 'user1', email: 'john@example.com', username: 'ClassicJohn', avatar_url: null, subscription_tier: 'collector', saved_cars: [], created_at: '2024-01-01' },
  },
  {
    id: '4',
    thread_id: '2',
    user_id: 'user3',
    content: 'Agree with ClassicJohn. The top-tier stuff (RS, RSR, Speedster) will always be desirable. But I think standard 911 SCs and Carreras from the 80s might come back down to earth a bit. Still great cars, just maybe not $100k+ great.',
    created_at: '2024-02-11T09:00:00Z',
    updated_at: '2024-02-11T09:00:00Z',
    user: { id: 'user3', email: 'mike@example.com', username: 'MustangMike', avatar_url: null, subscription_tier: 'free', saved_cars: [], created_at: '2024-01-10' },
  },
];
